<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MailLoadTester</RootNamespace>
    <AssemblyName>MailLoadTester.Core</AssemblyName>
    <Version>2.8.10</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
  </ItemGroup>
</Project>
